# Generated by Django 2.0 on 2018-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_english', '0002_auto_20181023_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyenglish',
            name='created_time',
            field=models.CharField(max_length=20, verbose_name='图片原始时间'),
        ),
        migrations.AlterField(
            model_name='dailyenglish',
            name='pic_url',
            field=models.CharField(max_length=200, unique=True, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='dailyimg',
            name='img_url',
            field=models.CharField(max_length=100, unique=True, verbose_name='图片链接'),
        ),
    ]
