# Generated by Django 2.0 on 2018-10-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_english', '0003_auto_20181023_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquote',
            name='quote',
            field=models.CharField(max_length=100, unique=True, verbose_name='每日一句'),
        ),
    ]
